version: '3'
services:
  smart-staking:
    container_name: smart-staking
    image: nginx:alpine
    ports:
      - 3001:80
#    build: .

    volumes:
      - ./nginx/proxy.prod.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/www/dist
